#!/usr/bin/env bun
// Scan dist/ and emit a TypeScript module that imports every file as a Bun
// `file` import, so the compiled serve binary can carry the whole SPA inline.
//
// `import path from '…' with { type: 'file' }` is a Bun loader form: at runtime
// the import resolves to the file's absolute path, and the bundler embeds the
// bytes during `bun build --compile`. The generated module is therefore the
// only place that knows the actual file names (the hashed bundles change every
// build) and `serve.ts` reads from it without ever touching the filesystem at
// runtime.
//
// Re-run this every time the SPA rebuilds — `serve/build.ts` does so
// automatically.

import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { relative, resolve, sep } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const DIST = resolve(ROOT, 'dist');
const OUT = resolve(import.meta.dir, 'embedded.generated.ts');

if (!existsSync(DIST)) {
  console.error(`[generate-embed] ${DIST} does not exist. Run \`bun run build\` first.`);
  process.exit(1);
}

const files: string[] = [];
const walk = (dir: string): void => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(relative(DIST, full).split(sep).join('/'));
  }
};
walk(DIST);
files.sort();

// The keys in ASSETS are the URL paths the SPA expects: root-relative, with
// forward slashes. Vite writes dist/ with forward-slash structure on every
// platform, so the walk above yields them directly.
const imports = files
  .map(
    (rel, i) =>
      `import asset${i} from ${JSON.stringify(`../dist/${rel}`)} with { type: 'file' };`,
  )
  .join('\n');

const entries = files
  .map((rel, i) => `  ${JSON.stringify(rel)}: asset${i},`)
  .join('\n');

const body = `// Auto-generated by generate-embed.ts. Do not edit.
//
// Imports every file under dist/ as a Bun \`file\` import so the compiled
// binary inlines them. The set of keys must match the URLs the SPA actually
// requests (root-relative, forward-slash paths).
//
// \`bun run typecheck\` reports this file as unused-import / no-default-export
// noise because the loader form yields a path, not a module; the file is only
// reachable through serve.ts which imports \`ASSETS\`.
${imports}

const ASSETS: Record<string, string> = {
${entries}
};

export { ASSETS };
export const BASE_PATH = '/';
`;

writeFileSync(OUT, body);
console.log(`[generate-embed] wrote ${files.length} assets to ${relative(ROOT, OUT)}`);
