export const AI_CHANNELS = 16;
export const AO_CHANNELS = 8;
export const PARAM_CHANNELS = 32;

export const CHART_REDRAW_INTERVAL_MS = 500;
export const NON_SAVING_CHART_PREVIEW_POINTS = 768;
export const CHART_INPUT_INTERVAL_MS = 100;

export const HEALTH_RECOVERY_MAX_ATTEMPTS = 10;
export const HEALTH_RECOVERY_INTERVAL_MS = 5000;